#!/bin/bash

# CONFIGURACIÓN LOCAL
USUARIO_LOCAL="root"
PASSWORD_LOCAL="mandraque9191"
HOST_LOCAL="127.0.0.1"
PUERTO_LOCAL="33991"

# CONFIGURACIÓN REMOTA
DB_DESARROLLOS="desarrollos_inmobiliarios"
DB_TRAYAN="admconsorcio"
DB_FUNDACION="fundacion_hemofilia"
USUARIO_REMOTO="root"
PASSWORD_DESARROLLOS="mandraque91"
PASSWORD_FUNDACION="mandraque91"
PASSWORD_TRAYAN="mandraque91"
PUERTO_REMOTO="3306"

HOST_BUNKERSUR="bunkersur.dyndns.biz"
HOST_DESARROLLOS="31.220.49.128"
HOST_FUNDACION="fundacionh.dyndns.biz"
# HOST_FUNDACION="10.0.0.50"
HOST_TRAYAN="trayanadm.dyndns.biz"
URL_DB="/backupDB"
